apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: default
  labels:
    app: demo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: registry.cn-hangzhou.aliyuncs.com/mj-mirror/backend:138e3f7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
